import streamlit as st
import yfinance as yf
import pandas as pd
import mplfinance as mpf
from io import BytesIO
from datetime import datetime
from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.lib import colors
import base64

# ----------------------------------------------------------
# LOAD ALL NSE STOCK SYMBOLS
# ----------------------------------------------------------
@st.cache_data
def get_all_nse_stocks():
    try:
        url = "https://archives.nseindia.com/content/equities/EQUITY_L.csv"
        df = pd.read_csv(url)
        return [s + ".NS" for s in df["SYMBOL"].tolist()]
    except:
        return ["RELIANCE.NS", "TCS.NS", "INFY.NS"]

nse_list = get_all_nse_stocks()


# ----------------------------------------------------------
# MARKET CAP FORMAT
# ----------------------------------------------------------
def format_market_cap(val):
    try:
        if val >= 1e7:
            return f"₹{val/1e7:.2f} Cr"
        elif val >= 1e5:
            return f"₹{val/1e5:.2f} Lakh"
        elif val >= 1e3:
            return f"₹{val/1e3:.2f} Thousand"
        return f"₹{val}"
    except:
        return "N/A"


# ----------------------------------------------------------
# PE RATING
# ----------------------------------------------------------
def pe_rating(pe):
    if pe is None or pe <= 0:
        return "N/A"
    if pe < 20:
        return "Excellent"
    if pe <= 35:
        return "Good"
    return "Poor"


# ----------------------------------------------------------
# BUYING RECOMMENDATION
# ----------------------------------------------------------
def buying_recommendation(df):
    try:
        df["SMA20"] = df["Close"].rolling(20).mean()
        df["EMA20"] = df["Close"].ewm(span=20).mean()

        delta = df["Close"].diff()
        gain = delta.mask(delta < 0, 0).rolling(14).mean()
        loss = (-delta.mask(delta > 0, 0)).rolling(14).mean()

        rs = gain / loss
        df["RSI"] = 100 - (100 / (1 + rs))

        latest = df.iloc[-1]
        score = 0
        score += 40 if latest["Close"] > latest["SMA20"] else 0
        score += 40 if latest["Close"] > latest["EMA20"] else 0
        score += 20 if latest["RSI"] < 70 else 0
        return min(score, 100)
    except:
        return 50


# ----------------------------------------------------------
# PERFORMANCE
# ----------------------------------------------------------
def performance(df):
    perf = {}
    for days, label in [(21, "1 Month"), (63, "3 Month"), (126, "6 Month")]:
        if len(df) > days:
            perf[label] = round(((df["Close"].iloc[-1] - df["Close"].iloc[-days]) / df["Close"].iloc[-days]) * 100, 2)
        else:
            perf[label] = "N/A"
    return perf


# ----------------------------------------------------------
# IPO EXTRA DETAILS (SAFE STATIC)
# ----------------------------------------------------------
def get_ipo_extra_details():
    return {
        "Price Range": "N/A",
        "Issue Size": "N/A",
        "Lot Size": "N/A",
        "Subscription Rate": "N/A"
    }


# ----------------------------------------------------------
# PDF GENERATOR
# ----------------------------------------------------------
def generate_pdf(symbol, data):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)
    styles = getSampleStyleSheet()

    header_style = ParagraphStyle(
        "header", alignment=TA_CENTER, fontSize=18,
        textColor=colors.HexColor("#003366"), spaceAfter=14
    )

    section = ParagraphStyle(
        "section", fontSize=14,
        textColor=colors.HexColor("#0b5394"),
        fontName="Helvetica-Bold",
        spaceBefore=12, spaceAfter=6
    )

    body = ParagraphStyle("body", fontSize=10, spaceAfter=4)

    story = []
    now = datetime.now()

    story.append(Paragraph("STOCK ANALYSIS REPORT", header_style))
    story.append(Paragraph(
        f"Generated By: <b>Jayesh Thakor</b><br/>"
        f"Date: {now.strftime('%d-%m-%Y')} | Time: {now.strftime('%H:%M:%S')}",
        body
    ))

    for sec, lines in data.items():
        story.append(Paragraph(sec, section))
        for l in lines:
            story.append(Paragraph(l.replace("₹", "Rs."), body))

    doc.build(story)
    pdf = buffer.getvalue()
    buffer.close()
    return pdf


# ----------------------------------------------------------
# STREAMLIT UI
# ----------------------------------------------------------
st.set_page_config(page_title="Stock Market Analyzer", layout="wide")

st.markdown("<h1 style='text-align:center;color:#00ffcc;'>📈 Stock Market Analyzer — By Jayesh Thakor</h1>",
            unsafe_allow_html=True)

st.write("### 🔍 Search NSE Stock")

selected_stock = st.selectbox(
    "Type stock name:",
    nse_list,
    index=None,
    placeholder="Search here.."
)

if selected_stock:
    st.success(f"Selected: **{selected_stock}**")

    stock = yf.Ticker(selected_stock)
    df = stock.history(period="6mo")
    info = stock.info

    current = info.get("currentPrice", 0)
    prev = info.get("previousClose", current)
    momentum = round(((current - prev) / prev) * 100, 2)

    # IPO
    hist = stock.history(period="max")
    listing_date = hist.index[0].strftime("%d-%m-%Y") if not hist.empty else "N/A"
    listing_price = round(hist.iloc[0]["Open"], 2) if not hist.empty else "N/A"
    profit_pct = round(((current - listing_price) / listing_price) * 100, 2) if listing_price != "N/A" else "N/A"

    perf = performance(df)
    rec = buying_recommendation(df)
    ipo_extra = get_ipo_extra_details()

    # ---------------- SHOW REPORT ----------------
    st.subheader("📊 Stock Analysis Report")

    col1, col2, col3 = st.columns(3)
    col1.metric("Current Price", f"₹{current}")
    col2.metric("Momentum", f"{momentum} %")
    col3.metric("Market Cap", format_market_cap(info.get("marketCap", 0)))

    st.write("### 📌 IPO Details")
    st.write(f"**Listing Date:** {listing_date}")
    st.write(f"**Listing Price:** ₹{listing_price}")
    st.write(f"**Return since IPO:** {profit_pct}%")

    st.write("### 📌 Fundamentals")
    st.write(f"**P/E Ratio:** {info.get('trailingPE', 'N/A')} ({pe_rating(info.get('trailingPE'))})")

    st.write("### 📌 Performance")
    st.write(perf)

    st.write("### ⭐ Recommendation Score")
    st.progress(rec / 100)
    st.write(f"**Score:** {rec}")


